// <auto-generated />
using System;
using Fluid.BgService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fluid.BgService.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Fluid.Shared.Models.MachineMasterModel", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedPersonName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InitializationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<byte>("MachineType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("OemSerialNo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("UseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UseType")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetTag");

                    b.ToTable("MachineMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
